version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/app/shop
      - ..:/app
    ports:
      - "8000:8000"
    working_dir: /app/shop
    command: python manage.py runserver 0.0.0.0:8000 