"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Intégration de Sentry pour la surveillance des erreurs
# Désactivé temporairement en raison d'un problème de configuration
"""
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    # Activer Sentry uniquement en développement pour le moment
    # jusqu'à ce que nous résolvions les problèmes de déploiement
    if os.environ.get('ENVIRONMENT') != 'production':
        # Configuration simplifiée de Sentry
        sentry_sdk.init(
            dsn="https://79ca8e1804a7469d16ace9b011ee0f83e04509265539956736.ingest.us.sentry.io/4509265545134080",
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.5,
        )
except ImportError:
    # Sentry n'est pas installé, pas de problème en développement
    pass
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d7kd8rj$0*ps41$3ny+%r5p^szqofj7@*mmc$=hsyfbhm#&_x7'

# SECURITY WARNING: don't run with debug turned on in production!
# En développement: DEBUG=True (valeur par défaut)
# En production: réglez la variable d'environnement DEBUG sur 'False'
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Configuration spéciale pour tester les pages d'erreur même en mode DEBUG
# Cette configuration permet de voir la page 404 personnalisée en développement avec DEBUG=True
TEMPLATE_DEBUG = False

# En production, assurez-vous d'inclure tous les domaines/sous-domaines sur lesquels votre site est hébergé
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.railway.app', '*.railway.app', 'mpjfums-production.up.railway.app', 'mpjfums-production.railway.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # Whitenoise pour les fichiers statiques
    'django.contrib.staticfiles',
    'parfums',  # Notre application de boutique de parfums
    
    # Outils d'optimisation
    # 'compressor',        # Compression des assets CSS/JS - Désactivé car incompatible avec Django 5.2
    'imagekit',          # Optimisation des images
    # 'cacheops',        # Cache avancé basé sur Redis - Désactivé car incompatible avec Django 5.2
    'django_browser_reload', # Rechargement automatique en développement
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise middleware pour les fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware', # Rechargement automatique en développement
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'parfums' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'parfums.context_processors.debug',  # Notre context processor personnalisé
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Configuration de la base de données
# Utiliser PostgreSQL en production (Railway) et SQLite en développement
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
        )
    }
elif os.environ.get('POSTGRES_USER') and os.environ.get('POSTGRES_PASSWORD'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'railway'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('PGHOST', 'localhost'),
            'PORT': os.environ.get('PGPORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configuration de WhiteNoise pour les fichiers statiques en production
WHITENOISE_USE_FINDERS = True
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Make sure the staticfiles directory exists
os.makedirs(str(STATIC_ROOT), exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django-compressor settings - Désactivé car incompatible avec Django 5.2
"""
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]
"""

# Configuration StaticFiles standard sans compressor
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Configuration de mise en cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'mpjfums-cache',
    }
}

# Configuration CacheOps pour du cache avancé - Désactivé car incompatible avec Django 5.2
# En production, utilisez Redis si disponible
"""
if os.environ.get('REDIS_URL'):
    CACHEOPS_REDIS = os.environ.get('REDIS_URL')
    CACHEOPS_DEFAULTS = {
        'timeout': 60*60  # 1 heure
    }
    CACHEOPS = {
        'parfums.*': {'ops': 'all', 'timeout': 60*60*2},  # 2 heures pour les modèles de parfums
    }
else:
    # Utilisation du cache mémoire en développement
    CACHEOPS_ENABLED = False
"""
# Désactivation complète de cacheops
CACHEOPS_ENABLED = False

# Configuration pour les images Unsplash
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.Optimistic'
IMAGEKIT_CACHEFILE_DIR = 'CACHE/images'

# Configuration des en-têtes de sécurité
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 31536000  # 1 an
