# Generated by Django 5.2 on 2025-05-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='parfum',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parfum',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Texte alternatif pour l'image (important pour le SEO)", max_length=100),
        ),
        migrations.AddField(
            model_name='parfum',
            name='image_locale',
            field=models.ImageField(blank=True, null=True, upload_to='parfums/'),
        ),
        migrations.AddField(
            model_name='parfum',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160),
        ),
        migrations.AddField(
            model_name='parfum',
            name='notes_de_coeur',
            field=models.CharField(blank=True, help_text='Notes de coeur du parfum', max_length=255),
        ),
        migrations.AddField(
            model_name='parfum',
            name='notes_de_fond',
            field=models.CharField(blank=True, help_text='Notes de fond du parfum', max_length=255),
        ),
        migrations.AddField(
            model_name='parfum',
            name='notes_de_tete',
            field=models.CharField(blank=True, help_text='Notes de tête du parfum', max_length=255),
        ),
        migrations.AddField(
            model_name='parfum',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='parfum',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
