name: Django CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker image
        run: |
          docker build -t mpjfums-app .
          
      - name: Start Docker container
        run: |
          docker run -d -p 8000:8000 --name mpjfums-container mpjfums-app
          
      - name: Wait for Django app to be ready
        run: |
          sleep 10
          curl -s http://localhost:8000/shop/parfums/ || echo "App may not be ready yet, continuing..."
          
      - name: Run tests
        run: |
          docker exec mpjfums-container python /app/shop/manage.py test
          
      - name: Stop Docker container
        run: |
          docker stop mpjfums-container
          docker rm mpjfums-container 